//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bottles.Tests.Configuration {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class environment : global::System.Configuration.ApplicationSettingsBase {
        
        private static environment defaultInstance = ((environment)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new environment())));
        
        public static environment Default {
            get {
                return defaultInstance;
            }
        }
    }
}
